import { PaddleOcrMcpClient } from "./clients/paddleocr-client";
import { NotionMcpClient } from "./clients/notion-client";
import { createWorkflow } from "./graph";
import { LearnerProfile, LearningTask } from "./types";
import { FeedbackLoopManager } from "./utils/feedback-loop";
import * as readline from 'readline';

/**
 * main 函数串联样例：读取 demo 文档，执行四种任务，并输出结果。
 */
async function main(): Promise<void> {
  console.log("debugging: main started");
  
  // Instantiate real clients
  const ocrClient = new PaddleOcrMcpClient();
  const notionClient = new NotionMcpClient();

  // Get user input
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });

  const userQuery = await new Promise<string>((resolve) => {
    rl.question('请输入您的学习需求或问题 (按回车跳过): ', (answer) => {
      rl.close();
      resolve(answer);
    });
  });

  if (userQuery) {
    console.log(`debugging: received user query: "${userQuery}"`);
  }
  
  // Search for a parent page to use as the root for new pages
  console.log("debugging: searching for anchor page 'sophie'...");
  let parentPageId = "";
  try {
    const searchResult = await notionClient.searchPage("sophie");
    if (searchResult) {
      console.log(`debugging: found page "${searchResult.title}" (ID: ${searchResult.id})`);
      parentPageId = searchResult.id;
    } else {
      console.error("Error: Could not find a page named 'sophie'.");
      console.error("Please ensure the page exists and is shared with the Notion Integration (click '...' > 'Connect to' > select your integration).");
      process.exit(1);
    }
  } catch (error) {
    console.error("debugging: failed to search for parent page", error);
    process.exit(1);
  }

  if (!parentPageId) {
    console.error("Error: Could not find any Notion page to use as a parent. Please ensure you have at least one page in your workspace shared with the integration.");
    process.exit(1);
  }

  // Use the anchor page directly as the parent for new tasks
  // Removed the intermediate "Learning Session" page creation logic
  const sessionPageId = parentPageId;
  const sessionPageUrl = ""; // We don't have a specific session URL anymore, or we could query it if needed
  console.log(`debugging: using anchor page (${sessionPageId}) as root for this session.`);

  // Create LangGraph workflow
  const app = createWorkflow(ocrClient, notionClient);
  const feedbackManager = new FeedbackLoopManager();

  const learnerProfile: LearnerProfile = {
    learnerId: sessionPageId, // Use the anchor page as the parent for task pages
    competencyLevel: "中等",
    learningGoal: "巩固一次函数与应用题",
    preferredStyle: "讲解+计划"
  };

  // Tasks will be generated by the planning node
  const tasks: Array<LearningTask> = [];

  const demoImagePath = `${process.cwd()}/samples/demo1.jpg`;
  
  // Initial State
  const initialState = {
    imagePath: demoImagePath,
    learnerProfile,
    tasks,
    userQuery,
    currentTaskIndex: 0,
    generatedContents: [],
    createdPageIds: []
  };

  console.log("debugging: invoking graph");
  const finalState = await app.invoke(initialState);
  
  const finalTasks = finalState.tasks as LearningTask[];
  const pageIds = finalState.createdPageIds as string[];

  // Feedback loop
  finalTasks.forEach((task, index) => {
    feedbackManager.recordFeedback(task, 4.5 - index * 0.5, `示例反馈：${task.description}`);
  });
  const strategyNote = feedbackManager.getStrategyNote();
  console.log("debugging: strategy note", strategyNote);
  console.log("debugging: pipeline finished");
  
  if (sessionPageUrl) {
    console.log(`\n\n✅ 流程结束！\n🔗 会话容器页面 (Session Container): ${sessionPageUrl}\n(注意：这只是会话的父页面，具体生成的笔记请查看下方的子页面链接)`);
  } else {
    console.log(`\n\n✅ 流程结束！\n⚠️ 未能获取会话页面链接，请检查 Notion。Page ID: ${sessionPageId}\n`);
  }

  if (pageIds.length > 0) {
    console.log("🔗 本次运行创建的其他页面:");
    pageIds.forEach(id => console.log(`- Page ID: ${id} (请在 Notion 中搜索此 ID 或查看 Session Page 的子页面)`));
  }
  
  console.log("--- 执行结果摘要 ---");
  (finalState.generatedContents as string[]).forEach((content: string, idx: number) => {
    console.log(`\n[Task ${idx + 1}] Result:\n${content.slice(0, 200)}...`);
  });
}

// 调用 main 并捕获异常。
main().catch((error) => {
  console.error("debugging: pipeline failed", error);
  process.exitCode = 1;
});

