import { PaddleOcrMcpClient } from "./clients/paddleocr-client";
import { NotionMcpClient } from "./clients/notion-client";
import { createWorkflow } from "./graph";
import { LearnerProfile, LearningTask } from "./types";
import { FeedbackLoopManager } from "./utils/feedback-loop";
import * as readline from 'readline';

/**
 * main 函数串联样例：读取 demo 文档，执行四种任务，并输出结果。
 */
async function main(): Promise<void> {
  console.log("debugging: main started");
  
  // Instantiate real clients
  const ocrClient = new PaddleOcrMcpClient();
  const notionClient = new NotionMcpClient();

  // Get user input
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });

  const userQuery = await new Promise<string>((resolve) => {
    rl.question('请输入您的学习需求或问题 (按回车跳过): ', (answer) => {
      rl.close();
      resolve(answer);
    });
  });

  if (userQuery) {
    console.log(`debugging: received user query: "${userQuery}"`);
  }
  
  // Search for a parent page to use as the root for new pages
  // Note: Notion API requires a parent page for creating new pages. We cannot create a top-level page directly via API
  // unless we have access to the workspace root, which is not exposed as a simple ID.
  // We will search for a suitable anchor page.
  console.log("debugging: searching for anchor page 'Learning Dashboard'...");
  let parentPageId = "";
  try {
    const dashboardId = await notionClient.searchPage("Learning Dashboard");
    if (dashboardId) {
      parentPageId = dashboardId;
      console.log(`debugging: found anchor page ID (${parentPageId})`);
    } else {
      console.log("debugging: 'Learning Dashboard' not found, searching for any page to use as anchor...");
      const anyPageId = await notionClient.searchPage("");
      if (anyPageId) {
        parentPageId = anyPageId;
        console.log(`debugging: using fallback anchor page ID (${parentPageId})`);
      }
    }
  } catch (error) {
    console.error("debugging: failed to search for parent page", error);
  }

  if (!parentPageId) {
    console.error("Error: Could not find any Notion page to use as a parent. Please ensure you have at least one page in your workspace shared with the integration.");
    process.exit(1);
  }

  // Create a new Session Page under the found anchor page
  const sessionTitle = `Learning Session - ${new Date().toLocaleString()}`;
  console.log(`debugging: creating session page '${sessionTitle}' under anchor page...`);
  
  const sessionPagePayload = {
    parentPageId: parentPageId,
    title: sessionTitle,
    markdownContent: "# Learning Session\n\nGenerated by AI Agent.\n\nThis page contains the results of the current learning session.",
    properties: {
      priority: "High",
      type: "Session",
      dueDate: new Date().toISOString()
    }
  };

  const { id: sessionPageId, url: sessionPageUrl } = await notionClient.createPage(sessionPagePayload);
  console.log(`debugging: created session page ID (${sessionPageId})`);

  // Create LangGraph workflow
  const app = createWorkflow(ocrClient, notionClient);
  const feedbackManager = new FeedbackLoopManager();

  const learnerProfile: LearnerProfile = {
    learnerId: sessionPageId, // Use the new session page as the parent for task pages
    competencyLevel: "中等",
    learningGoal: "巩固一次函数与应用题",
    preferredStyle: "讲解+计划"
  };

  // Tasks will be generated by the planning node
  const tasks: Array<LearningTask> = [];

  const demoImagePath = `${process.cwd()}/samples/demo1.jpg`;
  
  // Initial State
  const initialState = {
    imagePath: demoImagePath,
    learnerProfile,
    tasks,
    userQuery,
    currentTaskIndex: 0,
    generatedContents: [],
    createdPageIds: []
  };

  console.log("debugging: invoking graph");
  const finalState = await app.invoke(initialState);
  
  const pageIds = finalState.createdPageIds;
  const finalTasks = finalState.tasks as LearningTask[];

  // Feedback loop
  finalTasks.forEach((task, index) => {
    feedbackManager.recordFeedback(task, 4.5 - index * 0.5, `示例反馈：${task.description}`);
  });
  const strategyNote = feedbackManager.getStrategyNote();
  console.log("debugging: strategy note", strategyNote);
  console.log("debugging: pipeline finished", pageIds);
  
  if (sessionPageUrl) {
    console.log(`\n\n✅ 流程结束！\n🔗 父页面链接 (Session Page): ${sessionPageUrl}\n`);
  } else {
    console.log(`\n\n✅ 流程结束！\n⚠️ 未能获取父页面链接，请检查 Notion。Page ID: ${sessionPageId}\n`);
  }
}

// 调用 main 并捕获异常。
main().catch((error) => {
  console.error("debugging: pipeline failed", error);
  process.exitCode = 1;
});

